package world

import (
	"ssh-gatewars/internal/core"
	"ssh-gatewars/internal/gamedata"
)

// TileMap is a 2D grid of tiles.
type TileMap struct {
	Width, Height int
	Tiles         []gamedata.TileType // row-major [y*Width + x]
	GatePos       core.Pos            // stargate location
	SpawnPos      core.Pos            // player spawn (near gate)
	Rooms         []Room              // rooms generated by BSP
}

// Room is a rectangular area in the map.
type Room struct {
	X, Y, W, H int
}

func (r Room) Center() core.Pos {
	return core.Pos{X: r.X + r.W/2, Y: r.Y + r.H/2}
}

func (r Room) Contains(p core.Pos) bool {
	return p.X >= r.X && p.X < r.X+r.W && p.Y >= r.Y && p.Y < r.Y+r.H
}

// NewTileMap creates a tile map filled with walls.
func NewTileMap(w, h int) *TileMap {
	tiles := make([]gamedata.TileType, w*h)
	for i := range tiles {
		tiles[i] = gamedata.TileWall
	}
	return &TileMap{
		Width:  w,
		Height: h,
		Tiles:  tiles,
	}
}

// InBounds checks if a position is within the map.
func (m *TileMap) InBounds(p core.Pos) bool {
	return p.X >= 0 && p.X < m.Width && p.Y >= 0 && p.Y < m.Height
}

// At returns the tile at position p.
func (m *TileMap) At(p core.Pos) gamedata.TileType {
	if !m.InBounds(p) {
		return gamedata.TileWall
	}
	return m.Tiles[p.Y*m.Width+p.X]
}

// Set places a tile at position p.
func (m *TileMap) Set(p core.Pos, t gamedata.TileType) {
	if m.InBounds(p) {
		m.Tiles[p.Y*m.Width+p.X] = t
	}
}

// IsWalkable returns true if a position can be walked on.
func (m *TileMap) IsWalkable(p core.Pos) bool {
	if !m.InBounds(p) {
		return false
	}
	info, ok := gamedata.Tiles[m.At(p)]
	if !ok {
		return false
	}
	return info.Walkable
}

// IsOpaque returns true if a tile blocks line of sight.
func (m *TileMap) IsOpaque(p core.Pos) bool {
	if !m.InBounds(p) {
		return true
	}
	info, ok := gamedata.Tiles[m.At(p)]
	if !ok {
		return true
	}
	return info.Opaque
}

// FloorPositions returns all walkable positions.
func (m *TileMap) FloorPositions() []core.Pos {
	var positions []core.Pos
	for y := 0; y < m.Height; y++ {
		for x := 0; x < m.Width; x++ {
			p := core.Pos{X: x, Y: y}
			if m.IsWalkable(p) {
				positions = append(positions, p)
			}
		}
	}
	return positions
}
